# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31d1cb54ced90700eadf123c6d035ea5c126197b7c1c6ad45c29f9435b4cca281713d7acb6d6a7a78ffeb44c613523e37cbaea7d6e89e3f5e750c8edf09b97dd

test:
  secret_key_base: c54157d5cfcfe70dccd0492671b19ba6ed36a4c71c5e66f836b17c0eaf7a18bc85d7c9761458cf9297cb24ed6a6e7c457f563340c1fc6b3f0d46630758a29c03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
